/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type StudentSearchItem struct {

	Id string `json:"id"`

	StudentId string `json:"studentId"`

	DisplayName string `json:"displayName"`

	FullName string `json:"fullName,omitempty"`

	AvatarUrl string `json:"avatarUrl,omitempty"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	ClassName *string `json:"className,omitempty"`
}
