/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type UserProfile struct {

	Id string `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	StudentId string `json:"studentId,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	FullName string `json:"fullName,omitempty"`

	AvatarUrl string `json:"avatarUrl,omitempty"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	ClassName string `json:"className,omitempty"`

	Role string `json:"role,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
