/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type GetProgress200Response struct {
	Success bool `json:"success,omitempty"`

	Data ProgressMatrix `json:"data,omitempty"`
}
