/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ProgressMatrixCellCompletedCriteriaInner struct {
	CriteriaDocId string `json:"criteriaDocId,omitempty"`

	CriteriaDocTitle string `json:"criteriaDocTitle,omitempty"`

	Score int32 `json:"score,omitempty"`

	EvidenceCount int32 `json:"evidenceCount,omitempty"`
}
