/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type PaginationMeta struct {
	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"pageSize,omitempty"`

	Total int32 `json:"total,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`
}
