/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type LeaderboardDetail struct {

	// Current rank position
	Rank int32 `json:"rank"`

	UserId string `json:"userId"`

	StudentId string `json:"studentId"`

	// Display name of the user
	UserName string `json:"userName"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	ClassName *string `json:"className,omitempty"`

	// Number of approved activity submissions
	TotalApproved int32 `json:"totalApproved"`

	// Sum of all approved scores
	TotalScore int32 `json:"totalScore"`

	CriteriaStats []LeaderboardCriteriaStat `json:"criteriaStats"`

	Awards []LeaderboardDetailAwardsInner `json:"awards"`
}
