/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type CreateEvidenceRequest struct {

	// Target activity ID
	ActivityId string `json:"activityId"`

	// Optional activity_criteria id this evidence is for (NULL = applies to whole activity)
	ActivityCriteriaId *string `json:"activityCriteriaId,omitempty"`

	// R2 object key for the uploaded file
	FileKey string `json:"fileKey"`

	// Optional description of the evidence
	Description string `json:"description,omitempty"`
}
