/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type LeaderboardItem struct {
	Rank int32 `json:"rank,omitempty"`

	UserId string `json:"userId,omitempty"`

	UserName string `json:"userName,omitempty"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	TotalApproved int32 `json:"totalApproved,omitempty"`

	TotalScore int32 `json:"totalScore,omitempty"`
}
