/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ProgressMatrix struct {

	UserId string `json:"userId,omitempty"`

	Activities []ProgressMatrixCell `json:"activities,omitempty"`

	CriteriaScores []ProgressMatrixCriteriaScoresInner `json:"criteriaScores,omitempty"`
}
