/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ApiResponse struct {

	// Indicates if the request was successful
	Success bool `json:"success,omitempty"`

	// Response data payload
	Data *map[string]interface{} `json:"data,omitempty"`
}
