/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type NotificationItem struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Message string `json:"message"`

	Type string `json:"type"`

	IsRead bool `json:"isRead"`

	Data map[string]interface{} `json:"data,omitempty"`

	CreatedAt time.Time `json:"createdAt"`
}
