/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type AwardEvidenceInfo struct {

	EvidenceId string `json:"evidenceId,omitempty"`

	Criteria string `json:"criteria,omitempty"`

	AwardLevel *string `json:"awardLevel,omitempty"`

	Score *int32 `json:"score,omitempty"`

	FileUrl *string `json:"fileUrl,omitempty"`

	Description *string `json:"description,omitempty"`

	CreatedAt *time.Time `json:"createdAt,omitempty"`
}
