/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type GetActivityDetail404Response struct {

	Error string `json:"error,omitempty"`
}
