/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ProgressMatrixCell struct {
	ActivityId string `json:"activityId,omitempty"`

	ActivityTitle string `json:"activityTitle,omitempty"`

	TotalScore int32 `json:"totalScore,omitempty"`

	CompletedCriteria []ProgressMatrixCellCompletedCriteriaInner `json:"completedCriteria,omitempty"`
}
