/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type BulkReviewEvidenceRequest struct {

	// Evidence IDs to review with the same decision
	Ids []string `json:"ids"`

	// Bulk review decision
	Status string `json:"status"`

	// Optional feedback applied to all selected evidences
	ReviewNote *string `json:"reviewNote,omitempty"`
}
