/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type AuthResponse struct {
	User UserProfile `json:"user,omitempty"`

	AccessToken string `json:"accessToken,omitempty"`

	RefreshToken string `json:"refreshToken,omitempty"`
}
