/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ErrorResponseError struct {
	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Details map[string]interface{} `json:"details,omitempty"`
}
