/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ErrorResponseError struct {

	// Machine-readable error code
	Code string `json:"code,omitempty"`

	// Human-readable error message
	Message string `json:"message,omitempty"`

	// Additional error details (optional)
	Details *map[string]interface{} `json:"details,omitempty"`
}
