/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type LeaderboardCriteriaStat struct {

	Criteria string `json:"criteria"`

	Label string `json:"label"`

	// Number of approved activities/evidences counted for this criterion
	ApprovedActivities int32 `json:"approvedActivities"`
}
