/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type EvidenceItem struct {

	Id string `json:"id,omitempty"`

	ActivityId string `json:"activityId,omitempty"`

	ActivityTitle string `json:"activityTitle,omitempty"`

	CriteriaDocId string `json:"criteriaDocId,omitempty"`

	CriteriaDocTitle string `json:"criteriaDocTitle,omitempty"`

	FileUrl string `json:"fileUrl,omitempty"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	// Note from reviewer
	ReviewNote string `json:"reviewNote,omitempty"`

	ReviewedBy string `json:"reviewedBy,omitempty"`

	ReviewedAt time.Time `json:"reviewedAt,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
