/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type AdminEvidenceStats struct {
	Pending int32 `json:"pending"`

	ApprovedToday int32 `json:"approvedToday"`

	RejectedToday int32 `json:"rejectedToday"`

	Total int32 `json:"total"`
}
