/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type CreateEvidenceRequest struct {

	ActivityId string `json:"activityId"`

	CriteriaDocId string `json:"criteriaDocId,omitempty"`

	FileKey string `json:"fileKey"`

	Description string `json:"description,omitempty"`
}
