/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ProgressMatrixCriteriaScoresInner struct {

	Criteria string `json:"criteria,omitempty"`

	Label string `json:"label,omitempty"`

	// Total score for the criterion after participation and award points
	Score int32 `json:"score,omitempty"`

	MaxScore int32 `json:"maxScore,omitempty"`

	// Score from approved participation count
	ParticipationScore int32 `json:"participationScore,omitempty"`

	// Score from the highest award level within the criterion
	AwardScore int32 `json:"awardScore,omitempty"`

	// Number of approved activities counted for this criterion
	ApprovedActivityCount int32 `json:"approvedActivityCount,omitempty"`

	AwardLevel string `json:"awardLevel,omitempty"`
}
