/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type RegisterRequest struct {

	Email string `json:"email"`

	Password string `json:"password"`

	StudentId string `json:"studentId"`

	DisplayName string `json:"displayName,omitempty"`
}
