/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ReviewEvidenceRequest struct {

	// Review decision
	Status string `json:"status"`

	// Optional feedback for the student
	ReviewNote string `json:"reviewNote,omitempty"`

	// Allow re-reviewing already reviewed evidence
	ForceOverride bool `json:"forceOverride,omitempty"`
}
