/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type EvidenceItem struct {

	Id string `json:"id,omitempty"`

	ActivityId string `json:"activityId,omitempty"`

	ActivityTitle string `json:"activityTitle,omitempty"`

	// Optional FK to activity_criteria when evidence applies to a single criterion
	ActivityCriteriaId *string `json:"activityCriteriaId,omitempty"`

	// Score assigned by reviewer when evidence is approved; null = not reviewed
	Score *int32 `json:"score,omitempty"`

	FileUrl string `json:"fileUrl,omitempty"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	// Activity review level associated with the evidence
	ReviewLevel *string `json:"reviewLevel,omitempty"`

	// Note from reviewer
	ReviewNote *string `json:"reviewNote,omitempty"`

	ReviewedBy *string `json:"reviewedBy,omitempty"`

	ReviewedAt *time.Time `json:"reviewedAt,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
