/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type LeaderboardItem struct {

	// Current rank position
	Rank int32 `json:"rank,omitempty"`

	UserId string `json:"userId,omitempty"`

	StudentId string `json:"studentId,omitempty"`

	// Display name of the user
	UserName string `json:"userName,omitempty"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	// Number of approved evidence submissions
	TotalApproved int32 `json:"totalApproved,omitempty"`

	// Sum of all approved scores
	TotalScore int32 `json:"totalScore,omitempty"`
}
