/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ActivityDetail struct {

	Id string `json:"id,omitempty"`

	Slug string `json:"slug,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	ShortDescription string `json:"shortDescription,omitempty"`

	Location string `json:"location,omitempty"`

	TargetAudience string `json:"targetAudience,omitempty"`

	Rules string `json:"rules,omitempty"`

	Rewards string `json:"rewards,omitempty"`

	ContactInfo string `json:"contactInfo,omitempty"`

	ThumbnailUrl string `json:"thumbnailUrl,omitempty"`

	UnitId string `json:"unitId,omitempty"`

	UnitName string `json:"unitName,omitempty"`

	StartDate string `json:"startDate,omitempty"`

	EndDate string `json:"endDate,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	RegistrationUrl string `json:"registrationUrl,omitempty"`

	ReviewLevel string `json:"reviewLevel,omitempty"`

	Organizer string `json:"organizer,omitempty"`

	CriteriaDocs []CriteriaDoc `json:"criteriaDocs,omitempty"`
}
