/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ActivityItem struct {
	Id string `json:"id,omitempty"`

	Slug string `json:"slug,omitempty"`

	Title string `json:"title,omitempty"`

	ShortDescription string `json:"shortDescription,omitempty"`

	Location *string `json:"location,omitempty"`

	TargetAudience *string `json:"targetAudience,omitempty"`

	Rules *string `json:"rules,omitempty"`

	Rewards *string `json:"rewards,omitempty"`

	ContactInfo *string `json:"contactInfo,omitempty"`

	ThumbnailUrl string `json:"thumbnailUrl,omitempty"`

	UnitId *string `json:"unitId,omitempty"`

	UnitName *string `json:"unitName,omitempty"`

	StartDate string `json:"startDate,omitempty"`

	EndDate string `json:"endDate,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	RegistrationUrl *string `json:"registrationUrl,omitempty"`

	ReviewLevel string `json:"reviewLevel,omitempty"`

	Criteria []string `json:"criteria,omitempty"`

	Organizer *string `json:"organizer,omitempty"`

	// Number of distinct students with submitted evidence for this activity
	ParticipantCount int32 `json:"participantCount,omitempty"`

	// Total submitted evidences for this activity
	EvidenceCount int32 `json:"evidenceCount,omitempty"`

	// Number of pending evidences for this activity
	PendingEvidenceCount int32 `json:"pendingEvidenceCount,omitempty"`

	// Sum of configured activity criteria scores
	TotalScore int32 `json:"totalScore,omitempty"`

	// Admin creator display name when available
	CreatedByName *string `json:"createdByName,omitempty"`
}
