/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type AwardActivityOverview struct {

	ActivityId string `json:"activityId,omitempty"`

	ActivityTitle string `json:"activityTitle,omitempty"`

	ReviewLevel *string `json:"reviewLevel,omitempty"`

	Criteria []string `json:"criteria,omitempty"`

	AwardStats AwardActivityStats `json:"awardStats,omitempty"`

	TotalStudents int32 `json:"totalStudents,omitempty"`

	Students []AwardStudentOverview `json:"students,omitempty"`
}
