/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type AwardStudentOverview struct {

	UserId string `json:"userId,omitempty"`

	UserFullName *string `json:"userFullName,omitempty"`

	UserStudentId *string `json:"userStudentId,omitempty"`

	ClassName *string `json:"className,omitempty"`

	Evidences []AwardEvidenceInfo `json:"evidences,omitempty"`
}
