/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type AwardActivityStats struct {

	NHAT int32 `json:"NHAT,omitempty"`

	NHI int32 `json:"NHI,omitempty"`

	BA int32 `json:"BA,omitempty"`

	KHUYEN_KHICH int32 `json:"KHUYEN_KHICH,omitempty"`

	NONE int32 `json:"NONE,omitempty"`
}
