/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type AwardEvidenceItem struct {

	Id string `json:"id,omitempty"`

	UserId string `json:"userId,omitempty"`

	UserFullName *string `json:"userFullName,omitempty"`

	UserStudentId *string `json:"userStudentId,omitempty"`

	UserClassName *string `json:"userClassName,omitempty"`

	UserUnitId *string `json:"userUnitId,omitempty"`

	UserUnitName *string `json:"userUnitName,omitempty"`

	ActivityId string `json:"activityId,omitempty"`

	ActivityTitle string `json:"activityTitle,omitempty"`

	Criteria []string `json:"criteria,omitempty"`

	// Current score assigned to this evidence
	Score *int32 `json:"score,omitempty"`

	AwardLevel *string `json:"awardLevel,omitempty"`

	ReviewedAt *time.Time `json:"reviewedAt,omitempty"`
}
