/*
 * Ban Do 5 Tot API
 *
 * Backend API for Ban Do 5 Tot project
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the ActivitiesAPI part of the API
	ActivitiesAPI ActivitiesAPI
	// Routes for the AdminAPI part of the API
	AdminAPI AdminAPI
	// Routes for the AuthAPI part of the API
	AuthAPI AuthAPI
	// Routes for the EvidencesAPI part of the API
	EvidencesAPI EvidencesAPI
	// Routes for the HealthAPI part of the API
	HealthAPI HealthAPI
	// Routes for the LeaderboardAPI part of the API
	LeaderboardAPI LeaderboardAPI
	// Routes for the MediaAPI part of the API
	MediaAPI MediaAPI
	// Routes for the NotificationsAPI part of the API
	NotificationsAPI NotificationsAPI
	// Routes for the ProfileAPI part of the API
	ProfileAPI ProfileAPI
	// Routes for the ProgressAPI part of the API
	ProgressAPI ProgressAPI
	// Routes for the StudentsAPI part of the API
	StudentsAPI StudentsAPI
	// Routes for the UnitsAPI part of the API
	UnitsAPI UnitsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"GetActivityDetail",
			http.MethodGet,
			"/activities/:slug",
			handleFunctions.ActivitiesAPI.GetActivityDetail,
		},
		{
			"InviteActivity",
			http.MethodPost,
			"/activities/:slug/invites",
			handleFunctions.ActivitiesAPI.InviteActivity,
		},
		{
			"ListActivities",
			http.MethodGet,
			"/activities",
			handleFunctions.ActivitiesAPI.ListActivities,
		},
		{
			"BulkReviewEvidence",
			http.MethodPatch,
			"/admin/evidences/review-bulk",
			handleFunctions.AdminAPI.BulkReviewEvidence,
		},
		{
			"CreateActivity",
			http.MethodPost,
			"/admin/activities",
			handleFunctions.AdminAPI.CreateActivity,
		},
		{
			"DeleteActivity",
			http.MethodDelete,
			"/admin/activities/:id",
			handleFunctions.AdminAPI.DeleteActivity,
		},
		{
			"GetAdminEvidenceStats",
			http.MethodGet,
			"/admin/evidences/stats",
			handleFunctions.AdminAPI.GetAdminEvidenceStats,
		},
		{
			"ListAdminActivities",
			http.MethodGet,
			"/admin/activities",
			handleFunctions.AdminAPI.ListAdminActivities,
		},
		{
			"ListAdminEvidences",
			http.MethodGet,
			"/admin/evidences",
			handleFunctions.AdminAPI.ListAdminEvidences,
		},
		{
			"NotifyActivitiesBulk",
			http.MethodPost,
			"/admin/activities/notifications/bulk",
			handleFunctions.AdminAPI.NotifyActivitiesBulk,
		},
		{
			"NotifyActivity",
			http.MethodPost,
			"/admin/activities/:id/notifications",
			handleFunctions.AdminAPI.NotifyActivity,
		},
		{
			"NotifyDeadlineSoon",
			http.MethodPost,
			"/admin/activities/notifications/deadline-soon",
			handleFunctions.AdminAPI.NotifyDeadlineSoon,
		},
		{
			"ReviewEvidence",
			http.MethodPatch,
			"/admin/evidences/:id/review",
			handleFunctions.AdminAPI.ReviewEvidence,
		},
		{
			"UpdateActivity",
			http.MethodPatch,
			"/admin/activities/:id",
			handleFunctions.AdminAPI.UpdateActivity,
		},
		{
			"Login",
			http.MethodPost,
			"/auth/login",
			handleFunctions.AuthAPI.Login,
		},
		{
			"Logout",
			http.MethodPost,
			"/auth/logout",
			handleFunctions.AuthAPI.Logout,
		},
		{
			"Me",
			http.MethodGet,
			"/auth/me",
			handleFunctions.AuthAPI.Me,
		},
		{
			"Refresh",
			http.MethodPost,
			"/auth/refresh",
			handleFunctions.AuthAPI.Refresh,
		},
		{
			"Register",
			http.MethodPost,
			"/auth/register",
			handleFunctions.AuthAPI.Register,
		},
		{
			"CreateEvidence",
			http.MethodPost,
			"/evidences",
			handleFunctions.EvidencesAPI.CreateEvidence,
		},
		{
			"DeleteEvidence",
			http.MethodDelete,
			"/evidences/:id",
			handleFunctions.EvidencesAPI.DeleteEvidence,
		},
		{
			"ListEvidences",
			http.MethodGet,
			"/evidences",
			handleFunctions.EvidencesAPI.ListEvidences,
		},
		{
			"Healthz",
			http.MethodGet,
			"/healthz",
			handleFunctions.HealthAPI.Healthz,
		},
		{
			"Readyz",
			http.MethodGet,
			"/readyz",
			handleFunctions.HealthAPI.Readyz,
		},
		{
			"GetLeaderboardDetail",
			http.MethodGet,
			"/leaderboard/:studentId",
			handleFunctions.LeaderboardAPI.GetLeaderboardDetail,
		},
		{
			"ListLeaderboard",
			http.MethodGet,
			"/leaderboard",
			handleFunctions.LeaderboardAPI.ListLeaderboard,
		},
		{
			"UploadMedia",
			http.MethodPost,
			"/media/upload",
			handleFunctions.MediaAPI.UploadMedia,
		},
		{
			"ListNotifications",
			http.MethodGet,
			"/notifications",
			handleFunctions.NotificationsAPI.ListNotifications,
		},
		{
			"MarkAllNotificationsRead",
			http.MethodPatch,
			"/notifications/read-all",
			handleFunctions.NotificationsAPI.MarkAllNotificationsRead,
		},
		{
			"MarkNotificationRead",
			http.MethodPatch,
			"/notifications/:id/read",
			handleFunctions.NotificationsAPI.MarkNotificationRead,
		},
		{
			"GetProfile",
			http.MethodGet,
			"/profile",
			handleFunctions.ProfileAPI.GetProfile,
		},
		{
			"UpdateProfile",
			http.MethodPatch,
			"/profile",
			handleFunctions.ProfileAPI.UpdateProfile,
		},
		{
			"GetProgress",
			http.MethodGet,
			"/progress",
			handleFunctions.ProgressAPI.GetProgress,
		},
		{
			"SearchStudents",
			http.MethodGet,
			"/students/search",
			handleFunctions.StudentsAPI.SearchStudents,
		},
		{
			"ListUnits",
			http.MethodGet,
			"/units",
			handleFunctions.UnitsAPI.ListUnits,
		},
	}
}
