import type { UserProfile, EvidenceItem } from "@/services/generated/api";
import type { ProgressItem } from "./types";

export const mockUser: UserProfile = {
  id: "user_1",
  email: "a@example.com",
  fullName: "Nguyễn Văn A",
  studentId: "22040001",
  className: "K56A",
  unitId: "unit_1",
  unitName: "Khoa Ngôn ngữ & Văn hóa Anh",
  avatarUrl: null,
};

export const mockEvidences: EvidenceItem[] = [
  {
    id: "ev_1",
    activityId: "act_1",
    activityTitle: "Cuộc thi Olympic Tin học cấp Trường",
    criteriaDocId: null,
    criteriaDocTitle: "Giấy chứng nhận đạt giải Ba",
    fileUrl: "",
    description: "Giấy chứng nhận đạt giải Ba",
    status: "approved",
    criterionType: "HOC_TAP",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-09-15",
  },
  {
    id: "ev_2",
    activityId: "act_2",
    activityTitle: "Hội thảo Nghiên cứu Khoa học",
    criteriaDocId: null,
    criteriaDocTitle: "Báo cáo NCKH đạt loại Giỏi",
    fileUrl: "",
    description: "Báo cáo NCKH đạt loại Giỏi",
    status: "pending",
    criterionType: "HOC_TAP",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-10-01",
  },
  {
    id: "ev_3",
    activityId: "act_3",
    activityTitle: "Giải chạy Vì sức khỏe cộng đồng",
    criteriaDocId: null,
    criteriaDocTitle: "Chứng nhận tham gia giải chạy",
    fileUrl: "",
    description: "Chứng nhận tham gia giải chạy",
    status: "rejected",
    criterionType: "THE_LUC",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-08-20",
  },
  {
    id: "ev_4",
    activityId: "act_4",
    activityTitle: "Chiến dịch Mùa hè xanh",
    criteriaDocId: null,
    criteriaDocTitle: "Tham gia chiến dịch tình nguyện tại Hà Giang",
    fileUrl: "",
    description: "Tham gia chiến dịch tình nguyện tại Hà Giang",
    status: "approved",
    criterionType: "TINH_NGUYEN",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-07-10",
  },
  {
    id: "ev_5",
    activityId: "act_5",
    activityTitle: "Cuộc thi Hùng biện tiếng Anh",
    criteriaDocId: null,
    criteriaDocTitle: "Giải Nhì cuộc thi Hùng biện",
    fileUrl: "",
    description: "Giải Nhì cuộc thi Hùng biện",
    status: "approved",
    criterionType: "HOI_NHAP",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-11-05",
  },
  {
    id: "ev_6",
    activityId: "act_6",
    activityTitle: "Hoạt động ngoại khóa Đoàn trường",
    criteriaDocId: null,
    criteriaDocTitle: "Giấy khen của Đoàn trường",
    fileUrl: "",
    description: "Giấy khen của Đoàn trường",
    status: "approved",
    criterionType: "DAO_DUC",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-06-15",
  },
  {
    id: "ev_7",
    activityId: "act_7",
    activityTitle: "Kỳ thi đánh giá năng lực ngoại ngữ",
    criteriaDocId: null,
    criteriaDocTitle: "IELTS 7.0",
    fileUrl: "",
    description: "IELTS 7.0",
    status: "pending",
    criterionType: "HOI_NHAP",
    reviewLevel: "DHQGHN",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-12-01",
  },
  {
    id: "ev_8",
    activityId: "act_8",
    activityTitle: "Ngày hội hiến máu tình nguyện",
    criteriaDocId: null,
    criteriaDocTitle: "Hiến máu nhân đạo lần thứ 3",
    fileUrl: "",
    description: "Hiến máu nhân đạo lần thứ 3",
    status: "approved",
    criterionType: "TINH_NGUYEN",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-20",
  },
  {
    id: "ev_9",
    activityId: "act_9",
    activityTitle: "Giải bóng đá sinh viên",
    criteriaDocId: null,
    criteriaDocTitle: "Tham gia giải bóng đá cấp Khoa",
    fileUrl: "",
    description: "Tham gia giải bóng đá cấp Khoa",
    status: "pending",
    criterionType: "THE_LUC",
    reviewLevel: "TRUONG",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-11-20",
  },
  {
    id: "ev_10",
    activityId: "act_10",
    activityTitle: "Đánh giá Đoàn viên năm học",
    criteriaDocId: null,
    criteriaDocTitle: "Đoàn viên xuất sắc năm học 2024-2025",
    fileUrl: "",
    description: "Đoàn viên xuất sắc năm học 2024-2025",
    status: "approved",
    criterionType: "DAO_DUC",
    reviewLevel: "DHQGHN",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-09-30",
  },
  {
    id: "ev_11",
    activityId: "act_11",
    activityTitle: "Nghiên cứu khoa học sinh viên",
    criteriaDocId: null,
    criteriaDocTitle: "Bài báo đăng trên Tạp chí Khoa học ĐHQGHN",
    fileUrl: "",
    description: "Bài báo đăng trên Tạp chí Khoa học ĐHQGHN",
    status: "pending",
    criterionType: "HOC_TAP",
    reviewLevel: "DHQGHN",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-12-15",
  },
  {
    id: "ev_12",
    activityId: "act_12",
    activityTitle: "Giải thưởng tình nguyện",
    criteriaDocId: null,
    criteriaDocTitle: "Được trao giải Sao Tháng Giêng cấp ĐHQGHN",
    fileUrl: "",
    description: "Được trao giải Sao Tháng Giêng cấp ĐHQGHN",
    status: "approved",
    criterionType: "TINH_NGUYEN",
    reviewLevel: "DHQGHN",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-10-20",
  },
];

export const mockProgress: ProgressItem[] = [
  { criterion: "DAO_DUC", reviewLevel: "TRUONG", isCompleted: true },
  { criterion: "DAO_DUC", reviewLevel: "DHQGHN", isCompleted: false },
  { criterion: "DAO_DUC", reviewLevel: "THANH_PHO", isCompleted: false },
  { criterion: "DAO_DUC", reviewLevel: "TRUNG_UONG", isCompleted: false },
  { criterion: "HOC_TAP", reviewLevel: "TRUONG", isCompleted: true },
  { criterion: "HOC_TAP", reviewLevel: "DHQGHN", isCompleted: false },
  { criterion: "HOC_TAP", reviewLevel: "THANH_PHO", isCompleted: false },
  { criterion: "HOC_TAP", reviewLevel: "TRUNG_UONG", isCompleted: false },
  { criterion: "THE_LUC", reviewLevel: "TRUONG", isCompleted: false },
  { criterion: "THE_LUC", reviewLevel: "DHQGHN", isCompleted: false },
  { criterion: "THE_LUC", reviewLevel: "THANH_PHO", isCompleted: false },
  { criterion: "THE_LUC", reviewLevel: "TRUNG_UONG", isCompleted: false },
  { criterion: "TINH_NGUYEN", reviewLevel: "TRUONG", isCompleted: false },
  { criterion: "TINH_NGUYEN", reviewLevel: "DHQGHN", isCompleted: false },
  { criterion: "TINH_NGUYEN", reviewLevel: "THANH_PHO", isCompleted: false },
  { criterion: "TINH_NGUYEN", reviewLevel: "TRUNG_UONG", isCompleted: false },
  { criterion: "HOI_NHAP", reviewLevel: "TRUONG", isCompleted: false },
  { criterion: "HOI_NHAP", reviewLevel: "DHQGHN", isCompleted: false },
  { criterion: "HOI_NHAP", reviewLevel: "THANH_PHO", isCompleted: false },
  { criterion: "HOI_NHAP", reviewLevel: "TRUNG_UONG", isCompleted: false },
];
