export const badgeImages: Readonly<Record<string, string>> = {
  spec_dd_low: "/badges/criteria/spec_dd_low.png",
  spec_dd_high: "/badges/criteria/spec_dd_high.png",
  spec_ht_low: "/badges/criteria/spec_ht_low.png",
  spec_ht_high: "/badges/criteria/spec_ht_high.png",
  spec_tl_low: "/badges/criteria/spec_tl_low.png",
  spec_tl_high: "/badges/criteria/spec_tl_high.png",
  spec_tn_low: "/badges/criteria/spec_tn_low.png",
  spec_tn_high: "/badges/criteria/spec_tn_high.png",
  spec_hn_low: "/badges/criteria/spec_hn_low.png",
  spec_hn_high: "/badges/criteria/spec_hn_high.png",
  spec_multi_high: "/badges/criteria/spec_multi_high.png",
  spec_all_low: "/badges/criteria/spec_all_low.png",
  spec_all_high: "/badges/criteria/spec_all_high.png",
}

export const badgeIconImages: Readonly<Record<string, string>> = {
  spec_dd_low: "/badges/icons/spec_dd_low.png",
  spec_dd_high: "/badges/icons/spec_dd_high.png",
  spec_ht_low: "/badges/icons/spec_ht_low.png",
  spec_ht_high: "/badges/icons/spec_ht_high.png",
  spec_tl_low: "/badges/icons/spec_tl_low.png",
  spec_tl_high: "/badges/icons/spec_tl_high.png",
  spec_tn_low: "/badges/icons/spec_tn_low.png",
  spec_tn_high: "/badges/icons/spec_tn_high.png",
  spec_hn_low: "/badges/icons/spec_hn_low.png",
  spec_hn_high: "/badges/icons/spec_hn_high.png",
  spec_multi_high: "/badges/icons/spec_multi_high.png",
  spec_all_low: "/badges/icons/spec_all_low.png",
  spec_all_high: "/badges/icons/spec_all_high.png",
}
