export const badgeImages: Readonly<Record<string, string>> = {
  gen_c: "/badges/criteria/học tập tốt - cơ bản.png",
  gen_b: "/badges/criteria/hội nhập tốt - cơ bản.png",
  gen_a: "/badges/criteria/chiến binh bền bỉ.png",
  gen_a_plus: "/badges/criteria/huy chương.png",
  gen_s: "/badges/criteria/vòng nguyệt quế.png",
  spec_dd_low: "/badges/criteria/trái tim bản lĩnh.png",
  spec_dd_high: "/badges/criteria/công dân gương mẫu.png",
  spec_ht_low: "/badges/criteria/học tập tốt - cơ bản.png",
  spec_ht_high: "/badges/criteria/nhà bác học.png",
  spec_tl_low: "/badges/criteria/chiến binh bền bỉ.png",
  spec_tl_high: "/badges/criteria/ngọn lửa thể thao.png",
  spec_tn_low: "/badges/criteria/huy chương.png",
  spec_tn_high: "/badges/criteria/vòng nguyệt quế.png",
  spec_hn_low: "/badges/criteria/hội nhập tốt - cơ bản.png",
  spec_hn_high: "/badges/criteria/vòng nguyệt quế.png",
  spec_multi_low: "/badges/criteria/học tập tốt - cơ bản.png",
  spec_multi_high: "/badges/criteria/huy chương.png",
  spec_all_low: "/badges/criteria/hội nhập tốt - cơ bản.png",
  spec_all_high: "/badges/criteria/vòng nguyệt quế.png",
}

export const badgeIconImages: Readonly<Record<string, string>> = {
  gen_c: "/badges/icons/học_tập_tốt_-_cơ_bản-removebg-preview.png",
  gen_b: "/badges/icons/hội_nhập_tốt_-_cơ_bản-removebg-preview.png",
  gen_a: "/badges/icons/chiến_binh_bền_bỉ-removebg-preview.png",
  gen_a_plus: "/badges/icons/huy_chương-removebg-preview.png",
  gen_s: "/badges/icons/vòng_nguyệt_quế-removebg-preview.png",
  spec_dd_low: "/badges/icons/trái_tim_bản_lĩnh-removebg-preview.png",
  spec_dd_high: "/badges/icons/công_dân_gương_mẫu-removebg-preview.png",
  spec_ht_low: "/badges/icons/học_tập_tốt_-_cơ_bản-removebg-preview.png",
  spec_ht_high: "/badges/icons/nhà_bác_học-removebg-preview.png",
  spec_tl_low: "/badges/icons/chiến_binh_bền_bỉ-removebg-preview.png",
  spec_tl_high: "/badges/icons/ngọn_lửa_thể_thao-removebg-preview.png",
  spec_tn_low: "/badges/icons/huy_chương-removebg-preview.png",
  spec_tn_high: "/badges/icons/vòng_nguyệt_quế-removebg-preview.png",
  spec_hn_low: "/badges/icons/hội_nhập_tốt_-_cơ_bản-removebg-preview.png",
  spec_hn_high: "/badges/icons/vòng_nguyệt_quế-removebg-preview.png",
  spec_multi_low: "/badges/icons/học_tập_tốt_-_cơ_bản-removebg-preview.png",
  spec_multi_high: "/badges/icons/huy_chương-removebg-preview.png",
  spec_all_low: "/badges/icons/hội_nhập_tốt_-_cơ_bản-removebg-preview.png",
  spec_all_high: "/badges/icons/vòng_nguyệt_quế-removebg-preview.png",
}

